name: targetrk
channels:
  - defaults
dependencies:
  - ipywidgets=7.5.1=py_0
  - jupyter=1.0.0=py38_7
  - matplotlib=3.3.1=0
  - numpy=1.19.1
  - pandas=1.1.1
  - pickleshare=0.7.5=py38_1000
  - python=3.8.3
  - pip:
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
